# .scrutinizer.yml

build:

    dependencies:
        before:
            - rm composer.lock

    nodes:
        php56:
            environment:
                php:
                    version: 5.6

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage'
                        coverage:
                            file: 'coverage'
                            format: 'php-clover'

        php70:
            environment:
                php:
                    version: 7.0

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage'
                        coverage:
                            file: 'coverage'
                            format: 'php-clover'

        php71:
            environment:
                php:
                    version: 7.1

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage'
                        coverage:
                            file: 'coverage'
                            format: 'php-clover'

        php72:
            environment:
                php:
                    version: 7.2

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage'
                        coverage:
                            file: 'coverage'
                            format: 'php-clover'

        php73:
            environment:
                php:
                    version: 7.3

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage'
                        coverage:
                            file: 'coverage'
                            format: 'php-clover'


checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*



